### ISSUE TITLE
Running example on pypi doesn't do anything

### ISSUE THREAD

**Issue by turian** [kunitoki/popsicle#17]
I am on Apple silicon. I pip installed popsicle and ran the example in the pypi package. The script starts and just hangs, nothing appears. How can I diagnose this?

related #14

**Comment by kunitoki** [comment]
Pypi isn't tested much, some test could hang or crash and might depend on which cppyy is being used

**Comment by turian** [comment]
I'm happy to close the issue, but I would suggest that pip installation not be the first suggested installation path in the README, and perhaps "pip isn't tested much" be added.
