### ISSUE TITLE
Build for Apple Silicon

### ISSUE THREAD

**Issue by rv0** [kunitoki/popsicle#7]
I was trying to install on my Apple Silicon based computer (Apple M1 Macbook Air)

```
> pip3 install popsicle
ERROR: Could not find a version that satisfies the requirement popsicle (from versions: none)
ERROR: No matching distribution found for popsicle
```

So I tried to compile it by myself.
Install cmake and ninja with homebrew, then ran the steps as provided in the readme.

```
> python3 setup.py clean --all

running clean
'build/lib.macosx-11-arm64-3.9' does not exist -- can't clean it
'build/bdist.macosx-11-arm64' does not exist -- can't clean it
'build/scripts-3.9' does not exist -- can't clean it
```

That's suspicious, but continued nonetheless, wheel install fails eventually:

```
> pip3 install dist/popsicle-*.whl
ERROR: popsicle-0.0.8-py2.py3-none-macosx_11_arm64.whl is not a supported wheel on this platform.
```

Not sure what more I can try. Has anyone successfully used popsicle on M1 mac?

**EDIT:**
Tried again later, after removing the Homebrew python versions and updating to macOS 12 and the xcode commandline tools:
```
ERROR: popsicle-0.0.8-py2.py3-none-macosx_10_14_6_arm64.whl is not a supported wheel on this platform.
```
Not sure where it got the 10.14.6 this time :/ 

**EDIT2:**

Okay I figured it out:

```
> python3  -m pip debug -v | grep -A 10 'Compatible tags'
WARNING: This command is only meant for debugging. Do not use this with automation for parsing and getting these details, since the output and options of this command may change without notice.
Compatible tags: 334
  cp38-cp38-macosx_12_0_arm64
  cp38-cp38-macosx_12_0_universal2
  cp38-cp38-macosx_11_0_arm64
  cp38-cp38-macosx_11_0_universal2
  cp38-cp38-macosx_10_16_universal2
  cp38-cp38-macosx_10_15_universal2
  cp38-cp38-macosx_10_14_universal2
  cp38-cp38-macosx_10_13_universal2
  cp38-cp38-macosx_10_12_universal2
  cp38-cp38-macosx_10_11_universal2
```
After that I renamed the wheel in /dist to `popsicle-0.0.8-py2.py3-none-macosx_12_0_arm64.whl and I was able to install it.
Hope this info helps someone :)

***EDIT3:***

When I try to use the wheel I got, I get:

```
JUCE Assertion failure in juce_mac_SystemStats.mm:160
```

**Comment by kunitoki** [comment]
No i never tried it on M1, definately the build scripts needs to be adapted.

About the assertion, that is probably because the linked juce version is outdate prior to when they released M1 support, bumping the submodule to latest master should probably do the trick.

**Comment by rv0** [comment]
Yes, with latest JUCE master it works, cool!

**Comment by kunitoki** [comment]
I'm working to enable universal2 wheels. In the meantime you can launch python with rosetta `arch -x86_64 python popsicle_example.py`

**Comment by kunitoki** [comment]
I've pushed 0.0.9 for apple silicon. Can you check if it works for you?

**Comment by kunitoki** [comment]
Closing, apple silicon should be supported
