### ISSUE TITLE
Python AudioSource class not working

### ISSUE THREAD

**Issue by kangadrewie** [kunitoki/popsicle#8]
Hey there 👋 

Nice job on this!

I've noticed that the python implementation of AudioSource does not work? Particularly in the `audio_player_python.py` examples.

I've been trying to debug it but can't seem to solve the issue.

My python implementation is the same as the C++ yet only the C++ AudioAppComponent works. Any pointers on how to fix this?

You can try but running this example https://github.com/kunitoki/popsicle/blob/master/examples/audio_player_python.py

**Comment by kangadrewie** [comment]
Hey @kunitoki, got any idea on how I might fix this?

It seems `getNextAudioBlock` is not being called when trying to play a file? I'm happy to try open a PR to resolve if you have any hints of where to look? 

Thanks!

**Comment by kangadrewie** [comment]
I assume this was working at one point - anything introduced that would break this?

**Comment by kunitoki** [comment]
Thanks for reporting, will have a look

**Comment by kunitoki** [comment]
It could also be a bump in cppyy. Can you try to downgrade to 1.9?

**Comment by kunitoki** [comment]
I've pushed https://github.com/kunitoki/popsicle/commit/cfb80e3b385c13a09bb0d68eb106386b72b7632c and https://github.com/kunitoki/popsicle/commit/0ac87be4191b75720dfcb985f549961b2cd220d5 that should fix the issue. Can you confirm it works for you ?

I have no time to roll out a new version, but i'll try to do it next week.

**Comment by kunitoki** [comment]
I've releases 0.0.9 that should fix the issue. I get a cppyy unhandled exception on exit, but i will investigate and track that in a separate PR
